#!/usr/bin/env python3
#=========================================================================
# pipes/tb/framed/gen_pipevecs_framed.py
#=========================================================================
# Sebastian Claudiusz Magierowski Apr 18 2026

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
import sys


def make_data(idx: int) -> int:
    digit = idx + 1
    return (digit << 4) | digit


def parse_frame_pattern(frame_pattern: str) -> tuple[int, ...]:
    try:
        pattern = tuple(int(part) for part in frame_pattern.split(",") if part)
    except ValueError as exc:
        raise SystemExit("--frame-pattern must be a comma-separated list of positive integers") from exc

    if not pattern:
        raise SystemExit("--frame-pattern must contain at least one frame length")
    if any(length <= 0 for length in pattern):
        raise SystemExit("--frame-pattern entries must be positive")

    return pattern


def make_frame_tags(count: int, frame_pattern: tuple[int, ...]) -> list[tuple[int, int]]:
    tags: list[tuple[int, int]] = []
    produced = 0
    pattern_idx = 0

    while produced < count:
      frame_len = frame_pattern[pattern_idx % len(frame_pattern)]
      pattern_idx += 1
      actual_len = min(frame_len, count - produced)
      for pos in range(actual_len):
        first = 1 if pos == 0 else 0
        last = 1 if pos == actual_len - 1 else 0
        tags.append((first, last))
      produced += actual_len

    return tags


def pack_msg(first: int, last: int, data: int) -> int:
    return (first << 65) | (last << 64) | data


def render_vector_lines(stages: int, count: int, frame_pattern: tuple[int, ...], output: Path) -> str:
    lines: list[str] = []
    timestamp = datetime.now().isoformat(timespec="seconds")
    invocation = " ".join(sys.argv)
    tags = make_frame_tags(count, frame_pattern)

    lines.append("//========================================================================")
    lines.append(f"// {output.name}")
    lines.append("//========================================================================")
    lines.append("// Auto-generated framed pipe test vectors")
    lines.append(f"// Generated by : {Path(sys.argv[0]).name}")
    lines.append(f"// Invocation   : {invocation}")
    lines.append(f"// Parameters   : count={count}, stages={stages}, frame_pattern={frame_pattern}")
    lines.append(f"// Generated at : {timestamp}")
    lines.append("")

    lines.append("// Control program")
    lines.append("init_ctrl_src( 32'h0000_0000 ); // start word")
    lines.append(f"init_ctrl_src( 32'd{count} ); // number of framed beats")
    lines.append("init_ctrl_snk( 32'h0000_0001 ); // done word")
    lines.append("")

    lines.append("// Data source vectors: { first, last, data }")
    for idx, (first, last) in enumerate(tags):
        src_data = make_data(idx)
        src_msg = pack_msg(first, last, src_data)
        lines.append(
            f"init_data_src( 66'h{src_msg:017x} ); // first={first} last={last} data=0x{src_data:016x}"
        )
    lines.append("")

    lines.append(f"// Expected data sink vectors for a {stages}-stage framed pipe")
    for idx, (first, last) in enumerate(tags):
        src_data = make_data(idx)
        snk_data = src_data + stages
        snk_msg = pack_msg(first, last, snk_data)
        lines.append(
            f"init_data_snk( 66'h{snk_msg:017x} ); // first={first} last={last} data=0x{snk_data:016x}"
        )
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate framed pipe test vectors.")
    parser.add_argument("--stages", type=int, required=True, help="Number of +1 stages in the pipe.")
    parser.add_argument("--count", type=int, required=True, help="Number of framed beats.")
    parser.add_argument(
        "--frame-pattern",
        required=True,
        help="Comma-separated frame lengths, repeated until count beats are generated.",
    )
    parser.add_argument("--output", type=Path, required=True, help="Output include file.")
    args = parser.parse_args()

    if args.stages < 0:
        raise SystemExit("--stages must be non-negative")
    if args.count < 0:
        raise SystemExit("--count must be non-negative")

    frame_pattern = parse_frame_pattern(args.frame_pattern)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render_vector_lines(args.stages, args.count, frame_pattern, args.output),
        encoding="ascii",
    )


if __name__ == "__main__":
    main()
