#!/usr/bin/env python3
#=========================================================================
# pipes/tb/framer/gen_pipevecs_framer.py
#=========================================================================
# Sebastian Claudiusz Magierowski May 8 2026

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
import sys


def make_data(idx: int) -> int:
    digit = idx + 1
    return (digit << 4) | digit


def pack_framebits(first: int, last: int, data: int) -> int:
    return (first << 65) | (last << 64) | data


def render_vector_lines(count: int, frame_len: int, output: Path) -> str:
    lines: list[str] = []
    timestamp = datetime.now().isoformat(timespec="seconds")
    invocation = " ".join(sys.argv)

    lines.append("//========================================================================")
    lines.append(f"// {output.name}")
    lines.append("//========================================================================")
    lines.append("// Auto-generated framer test vectors")
    lines.append(f"// Generated by : {Path(sys.argv[0]).name}")
    lines.append(f"// Invocation   : {invocation}")
    lines.append(f"// Parameters   : count={count}, frame_len={frame_len}")
    lines.append(f"// Generated at : {timestamp}")
    lines.append("")

    lines.append("// Raw source vectors")
    for idx in range(count):
        data = make_data(idx)
        lines.append(f"init_raw_src( 64'h{data:016x} );")
    lines.append("")

    lines.append("// Expected framed sink vectors: { first, last, data }")
    for idx in range(count):
        data = make_data(idx)
        frame_idx = idx % frame_len
        first = 1 if frame_idx == 0 else 0
        last = 1 if (frame_idx == frame_len - 1) or (idx == count - 1) else 0
        msg = pack_framebits(first, last, data)
        lines.append(
            f"init_frm_snk( 66'h{msg:017x} ); // first={first} last={last} data=0x{data:016x}"
        )
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate pipe_framer test vectors.")
    parser.add_argument("--count", type=int, required=True, help="Number of raw beats.")
    parser.add_argument("--frame-len", type=int, required=True, help="Fixed frame length.")
    parser.add_argument("--output", type=Path, required=True, help="Output include file.")
    args = parser.parse_args()

    if args.count < 0:
        raise SystemExit("--count must be non-negative")
    if args.frame_len <= 0:
        raise SystemExit("--frame-len must be positive")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render_vector_lines(args.count, args.frame_len, args.output),
        encoding="ascii",
    )


if __name__ == "__main__":
    main()
