#!/usr/bin/env python3
#=========================================================================
# pipes/tb/framemeta/gen_pipevecs_framemeta.py
#=========================================================================
# Sebastian Claudiusz Magierowski May 4 2026

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
import sys


def make_data(idx: int) -> int:
    digit = idx + 1
    return (digit << 4) | digit


def parse_frame_pattern(frame_pattern: str) -> tuple[int, ...]:
    try:
        pattern = tuple(int(part) for part in frame_pattern.split(",") if part)
    except ValueError as exc:
        raise SystemExit("--frame-pattern must be a comma-separated list of positive integers") from exc

    if not pattern:
        raise SystemExit("--frame-pattern must contain at least one frame length")
    if any(length <= 0 for length in pattern):
        raise SystemExit("--frame-pattern entries must be positive")

    return pattern


def make_frame_tags(count: int, frame_pattern: tuple[int, ...]) -> list[tuple[int, int, int, int]]:
    tags: list[tuple[int, int, int, int]] = []
    produced = 0
    pattern_idx = 0
    frame_id = 0

    while produced < count:
      frame_len = frame_pattern[pattern_idx % len(frame_pattern)]
      pattern_idx += 1
      actual_len = min(frame_len, count - produced)
      for pos in range(actual_len):
        first = 1 if pos == 0 else 0
        last = 1 if pos == actual_len - 1 else 0
        tags.append((frame_id, pos, first, last))
      produced += actual_len
      frame_id += 1

    return tags


def pack_msg(
    frame_id: int,
    beat_idx: int,
    first: int,
    last: int,
    data: int,
    *,
    frame_id_nbits: int,
    beat_idx_nbits: int,
    data_nbits: int,
) -> int:
    return (
        (frame_id << (beat_idx_nbits + 2 + data_nbits))
        | (beat_idx << (2 + data_nbits))
        | (first << (1 + data_nbits))
        | (last << data_nbits)
        | data
    )


def render_vector_lines(
    stages: int,
    count: int,
    frame_pattern: tuple[int, ...],
    frame_id_nbits: int,
    beat_idx_nbits: int,
    data_nbits: int,
    output: Path,
) -> str:
    lines: list[str] = []
    timestamp = datetime.now().isoformat(timespec="seconds")
    invocation = " ".join(sys.argv)
    tags = make_frame_tags(count, frame_pattern)
    msg_nbits = frame_id_nbits + beat_idx_nbits + 2 + data_nbits
    msg_hex_digits = (msg_nbits + 3) // 4

    lines.append("//========================================================================")
    lines.append(f"// {output.name}")
    lines.append("//========================================================================")
    lines.append("// Auto-generated framemeta pipe test vectors")
    lines.append(f"// Generated by : {Path(sys.argv[0]).name}")
    lines.append(f"// Invocation   : {invocation}")
    lines.append(
        f"// Parameters   : count={count}, stages={stages}, frame_pattern={frame_pattern}, "
        f"frame_id_nbits={frame_id_nbits}, beat_idx_nbits={beat_idx_nbits}, data_nbits={data_nbits}"
    )
    lines.append(f"// Generated at : {timestamp}")
    lines.append("")

    lines.append("// Control program")
    lines.append("init_ctrl_src( 32'h0000_0000 ); // start word")
    lines.append(f"init_ctrl_src( 32'd{count} ); // number of framed beats")
    lines.append("init_ctrl_snk( 32'h0000_0001 ); // done word")
    lines.append("")

    lines.append("// Data source vectors: { frame_id, beat_idx, first, last, data }")
    for idx, (frame_id, beat_idx, first, last) in enumerate(tags):
        src_data = make_data(idx)
        src_msg = pack_msg(
            frame_id,
            beat_idx,
            first,
            last,
            src_data,
            frame_id_nbits=frame_id_nbits,
            beat_idx_nbits=beat_idx_nbits,
            data_nbits=data_nbits,
        )
        lines.append(
            f"init_data_src( {msg_nbits}'h{src_msg:0{msg_hex_digits}x} ); // frame_id={frame_id} beat_idx={beat_idx} first={first} last={last} data=0x{src_data:016x}"
        )
    lines.append("")

    lines.append(f"// Expected data sink vectors for a {stages}-stage framemeta pipe")
    for idx, (frame_id, beat_idx, first, last) in enumerate(tags):
        src_data = make_data(idx)
        snk_data = src_data + stages
        snk_msg = pack_msg(
            frame_id,
            beat_idx,
            first,
            last,
            snk_data,
            frame_id_nbits=frame_id_nbits,
            beat_idx_nbits=beat_idx_nbits,
            data_nbits=data_nbits,
        )
        lines.append(
            f"init_data_snk( {msg_nbits}'h{snk_msg:0{msg_hex_digits}x} ); // frame_id={frame_id} beat_idx={beat_idx} first={first} last={last} data=0x{snk_data:016x}"
        )
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate framemeta pipe test vectors.")
    parser.add_argument("--stages", type=int, required=True, help="Number of +1 stages in the pipe.")
    parser.add_argument("--count", type=int, required=True, help="Number of framed beats.")
    parser.add_argument(
        "--frame-pattern",
        required=True,
        help="Comma-separated frame lengths, repeated until count beats are generated.",
    )
    parser.add_argument("--frame-id-nbits", type=int, required=True, help="Number of frame_id metadata bits.")
    parser.add_argument("--beat-idx-nbits", type=int, required=True, help="Number of beat_idx metadata bits.")
    parser.add_argument("--data-nbits", type=int, required=True, help="Number of data bits.")
    parser.add_argument("--output", type=Path, required=True, help="Output include file.")
    args = parser.parse_args()

    if args.stages < 0:
        raise SystemExit("--stages must be non-negative")
    if args.count < 0:
        raise SystemExit("--count must be non-negative")
    if args.frame_id_nbits <= 0:
        raise SystemExit("--frame-id-nbits must be positive")
    if args.beat_idx_nbits <= 0:
        raise SystemExit("--beat-idx-nbits must be positive")
    if args.data_nbits <= 0:
        raise SystemExit("--data-nbits must be positive")

    frame_pattern = parse_frame_pattern(args.frame_pattern)
    tags = make_frame_tags(args.count, frame_pattern)
    max_frame_id = max((frame_id for frame_id, _, _, _ in tags), default=0)
    max_beat_idx = max((beat_idx for _, beat_idx, _, _ in tags), default=0)
    if max_frame_id >= (1 << args.frame_id_nbits):
        raise SystemExit("--frame-id-nbits is too small for generated frame ids")
    if max_beat_idx >= (1 << args.beat_idx_nbits):
        raise SystemExit("--beat-idx-nbits is too small for generated beat indices")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render_vector_lines(
            args.stages,
            args.count,
            frame_pattern,
            args.frame_id_nbits,
            args.beat_idx_nbits,
            args.data_nbits,
            args.output,
        ),
        encoding="ascii",
    )


if __name__ == "__main__":
    main()
