#!/usr/bin/env python3
#=========================================================================
# pipes/tb/framemetagen/gen_pipevecs_framemetagen.py
#=========================================================================
# Sebastian Claudiusz Magierowski May 8 2026
#
# Generate include-file test vectors for the integrated framemetagen pipe.
# The source side is raw data; the expected sink side is the generated
# `{ frame_id, beat_idx, first, last, data }` stream after each data beat has
# passed through the configured number of +1 pipeline stages.
#
# The generator must match the Verilog build settings: raw beat count, fixed
# frame length, pipeline stage count, and metadata/data field widths. Those
# settings determine the expected frame ids, beat indices, boundary bits, and
# final data values.

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
import sys


def make_data(idx: int) -> int:
    digit = idx + 1
    return (digit << 4) | digit


def make_frame_tags(count: int, frame_len: int) -> list[tuple[int, int, int, int]]:
    tags: list[tuple[int, int, int, int]] = []

    for idx in range(count):
        frame_id = idx // frame_len
        beat_idx = idx % frame_len
        first = 1 if beat_idx == 0 else 0
        last = 1 if (beat_idx + 1 == frame_len) or (idx + 1 == count) else 0
        tags.append((frame_id, beat_idx, first, last))

    return tags


def pack_msg(
    frame_id: int,
    beat_idx: int,
    first: int,
    last: int,
    data: int,
    *,
    frame_id_nbits: int,
    beat_idx_nbits: int,
    data_nbits: int,
) -> int:
    return (
        (frame_id << (beat_idx_nbits + 2 + data_nbits))
        | (beat_idx << (2 + data_nbits))
        | (first << (1 + data_nbits))
        | (last << data_nbits)
        | data
    )


def render_vector_lines(
    stages: int,
    count: int,
    frame_len: int,
    frame_id_nbits: int,
    beat_idx_nbits: int,
    data_nbits: int,
    output: Path,
) -> str:
    lines: list[str] = []
    timestamp = datetime.now().isoformat(timespec="seconds")
    invocation = " ".join(sys.argv)
    tags = make_frame_tags(count, frame_len)
    msg_nbits = frame_id_nbits + beat_idx_nbits + 2 + data_nbits
    msg_hex_digits = (msg_nbits + 3) // 4
    data_hex_digits = (data_nbits + 3) // 4

    lines.append("//========================================================================")
    lines.append(f"// {output.name}")
    lines.append("//========================================================================")
    lines.append("// Auto-generated framemetagen pipe test vectors")
    lines.append(f"// Generated by : {Path(sys.argv[0]).name}")
    lines.append(f"// Invocation   : {invocation}")
    lines.append(
        f"// Parameters   : count={count}, stages={stages}, frame_len={frame_len}, "
        f"frame_id_nbits={frame_id_nbits}, beat_idx_nbits={beat_idx_nbits}, data_nbits={data_nbits}"
    )
    lines.append(f"// Generated at : {timestamp}")
    lines.append("")

    lines.append("// Control program")
    lines.append("init_ctrl_src( 32'h0000_0000 ); // start word")
    lines.append(f"init_ctrl_src( 32'd{count} ); // number of raw input beats")
    lines.append("init_ctrl_snk( 32'h0000_0001 ); // done word")
    lines.append("")

    lines.append("// Raw data source vectors")
    for idx in range(count):
        src_data = make_data(idx)
        lines.append(f"init_data_src( {data_nbits}'h{src_data:0{data_hex_digits}x} );")
    lines.append("")

    lines.append(f"// Expected framemeta sink vectors for a {stages}-stage pipe")
    for idx, (frame_id, beat_idx, first, last) in enumerate(tags):
        snk_data = make_data(idx) + stages
        snk_msg = pack_msg(
            frame_id,
            beat_idx,
            first,
            last,
            snk_data,
            frame_id_nbits=frame_id_nbits,
            beat_idx_nbits=beat_idx_nbits,
            data_nbits=data_nbits,
        )
        lines.append(
            f"init_data_snk( {msg_nbits}'h{snk_msg:0{msg_hex_digits}x} ); // frame_id={frame_id} beat_idx={beat_idx} first={first} last={last} data=0x{snk_data:0{data_hex_digits}x}"
        )
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate framemetagen pipe test vectors.")
    parser.add_argument("--stages", type=int, required=True, help="Number of +1 stages in the pipe.")
    parser.add_argument("--count", type=int, required=True, help="Number of raw input beats.")
    parser.add_argument("--frame-len", type=int, required=True, help="Fixed frame length.")
    parser.add_argument("--frame-id-nbits", type=int, required=True, help="Number of frame_id metadata bits.")
    parser.add_argument("--beat-idx-nbits", type=int, required=True, help="Number of beat_idx metadata bits.")
    parser.add_argument("--data-nbits", type=int, required=True, help="Number of data bits.")
    parser.add_argument("--output", type=Path, required=True, help="Output include file.")
    args = parser.parse_args()

    if args.stages < 0:
        raise SystemExit("--stages must be non-negative")
    if args.count < 0:
        raise SystemExit("--count must be non-negative")
    if args.frame_len <= 0:
        raise SystemExit("--frame-len must be positive")
    if args.frame_id_nbits <= 0:
        raise SystemExit("--frame-id-nbits must be positive")
    if args.beat_idx_nbits <= 0:
        raise SystemExit("--beat-idx-nbits must be positive")
    if args.data_nbits <= 0:
        raise SystemExit("--data-nbits must be positive")

    tags = make_frame_tags(args.count, args.frame_len)
    max_frame_id = max((frame_id for frame_id, _, _, _ in tags), default=0)
    max_beat_idx = max((beat_idx for _, beat_idx, _, _ in tags), default=0)
    if max_frame_id >= (1 << args.frame_id_nbits):
        raise SystemExit("--frame-id-nbits is too small for generated frame ids")
    if max_beat_idx >= (1 << args.beat_idx_nbits):
        raise SystemExit("--beat-idx-nbits is too small for generated beat indices")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render_vector_lines(
            args.stages,
            args.count,
            args.frame_len,
            args.frame_id_nbits,
            args.beat_idx_nbits,
            args.data_nbits,
            args.output,
        ),
        encoding="ascii",
    )


if __name__ == "__main__":
    main()

