#!/usr/bin/env python3
#=========================================================================
# pipes/tb/framegen/gen_pipevecs_framegen.py
#=========================================================================
# Sebastian Claudiusz Magierowski May 8 2026

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
import sys


def make_data(idx: int) -> int:
    digit = idx + 1
    return (digit << 4) | digit


def make_frame_tags(count: int, frame_len: int) -> list[tuple[int, int]]:
    tags: list[tuple[int, int]] = []

    for idx in range(count):
        frame_idx = idx % frame_len
        first = 1 if frame_idx == 0 else 0
        last = 1 if (frame_idx + 1 == frame_len) or (idx + 1 == count) else 0
        tags.append((first, last))

    return tags


def pack_framebits(first: int, last: int, data: int) -> int:
    return (first << 65) | (last << 64) | data


def render_vector_lines(stages: int, count: int, frame_len: int, output: Path) -> str:
    lines: list[str] = []
    timestamp = datetime.now().isoformat(timespec="seconds")
    invocation = " ".join(sys.argv)
    tags = make_frame_tags(count, frame_len)

    lines.append("//========================================================================")
    lines.append(f"// {output.name}")
    lines.append("//========================================================================")
    lines.append("// Auto-generated framegen pipe test vectors")
    lines.append(f"// Generated by : {Path(sys.argv[0]).name}")
    lines.append(f"// Invocation   : {invocation}")
    lines.append(f"// Parameters   : count={count}, stages={stages}, frame_len={frame_len}")
    lines.append(f"// Generated at : {timestamp}")
    lines.append("")

    lines.append("// Control program")
    lines.append("init_ctrl_src( 32'h0000_0000 ); // start word")
    lines.append(f"init_ctrl_src( 32'd{count} ); // number of raw input beats")
    lines.append("init_ctrl_snk( 32'h0000_0001 ); // done word")
    lines.append("")

    lines.append("// Raw data source vectors")
    for idx in range(count):
        src_data = make_data(idx)
        lines.append(f"init_data_src( 64'h{src_data:016x} );")
    lines.append("")

    lines.append(f"// Expected framed data sink vectors for a {stages}-stage pipe")
    for idx, (first, last) in enumerate(tags):
        snk_data = make_data(idx) + stages
        snk_msg = pack_framebits(first, last, snk_data)
        lines.append(
            f"init_data_snk( 66'h{snk_msg:017x} ); // first={first} last={last} data=0x{snk_data:016x}"
        )
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate framegen pipe test vectors.")
    parser.add_argument("--stages", type=int, required=True, help="Number of +1 stages in the pipe.")
    parser.add_argument("--count", type=int, required=True, help="Number of raw input beats.")
    parser.add_argument("--frame-len", type=int, required=True, help="Fixed frame length.")
    parser.add_argument("--output", type=Path, required=True, help="Output include file.")
    args = parser.parse_args()

    if args.stages < 0:
        raise SystemExit("--stages must be non-negative")
    if args.count < 0:
        raise SystemExit("--count must be non-negative")
    if args.frame_len <= 0:
        raise SystemExit("--frame-len must be positive")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render_vector_lines(args.stages, args.count, args.frame_len, args.output),
        encoding="ascii",
    )


if __name__ == "__main__":
    main()

