#!/usr/bin/env python3
#=========================================================================
# pipes/tb/sched/gen_sched_trace.py
#=========================================================================
# Sebastian Claudiusz Magierowski May 14 2026
#
# Convert a human-authored schedule trace TSV into a Verilog include file.
# The TSV describes expected post-edge register state for each accepted
# miniature LPV input/drain epoch.
#
# Cell convention:
#   X      unknown/uninitialized, do not check valid or value
#   I      invalid, require valid=0 and ignore value bits
#   a,b    valid tuple encoded as { a[7:0], b[7:0] }

from __future__ import annotations

import argparse
import csv
from datetime import datetime
from pathlib import Path
import sys


REG_NAMES = (
    "A",
    "R0",
    "R1",
    "R2",
    "R3",
    "R4",
    "R5",
    "R6",
    "R7",
    "R8",
    "D2",
    "D3",
    "D4",
    "D5",
    "D6",
    "F6",
)

STATUS_X = 0
STATUS_I = 1
STATUS_V = 2


def parse_cell(cell: str, *, row_num: int, reg_name: str) -> tuple[int, int]:
    cell = cell.strip()

    if cell == "X":
        return STATUS_X, 0

    if cell == "I":
        return STATUS_I, 0

    parts = cell.split(",")
    if len(parts) != 2:
        raise SystemExit(f"row {row_num}: bad cell for {reg_name}: {cell!r}")

    try:
        x = int(parts[0], 10)
        y = int(parts[1], 10)
    except ValueError as exc:
        raise SystemExit(f"row {row_num}: bad tuple for {reg_name}: {cell!r}") from exc

    if not (0 <= x <= 255):
        raise SystemExit(f"row {row_num}: tuple x out of 8-bit range for {reg_name}: {cell!r}")
    if not (0 <= y <= 255):
        raise SystemExit(f"row {row_num}: tuple y out of 8-bit range for {reg_name}: {cell!r}")

    return STATUS_V, (x << 8) | y


def load_trace(path: Path) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []

    with path.open(newline="", encoding="utf-8-sig") as f:
        reader = csv.reader(f, delimiter="\t")
        try:
            raw_header = next(reader)
        except StopIteration as exc:
            raise SystemExit(f"{path}: empty trace file") from exc

        header = [entry.strip() for entry in raw_header if entry.strip()]
        expected_header = ["i", "k", *REG_NAMES]
        if header != expected_header:
            raise SystemExit(
                f"{path}: unexpected header\n"
                f"  expected: {expected_header}\n"
                f"  actual:   {header}"
            )

        for row_num, raw_row in enumerate(reader, start=2):
            if not any(cell.strip() for cell in raw_row):
                continue

            row = [entry.strip() for entry in raw_row[: len(expected_header)]]
            if len(row) < len(expected_header):
                raise SystemExit(f"row {row_num}: expected {len(expected_header)} columns, got {len(row)}")

            try:
                frame_i = int(row[0], 10)
                beat_k = int(row[1], 10)
            except ValueError as exc:
                raise SystemExit(f"row {row_num}: bad i/k fields: {row[:2]!r}") from exc

            regs: list[tuple[int, int]] = []
            for reg_name, cell in zip(REG_NAMES, row[2:]):
                regs.append(parse_cell(cell, row_num=row_num, reg_name=reg_name))

            rows.append(
                {
                    "i": frame_i,
                    "k": beat_k,
                    "regs": regs,
                }
            )

    if not rows:
        raise SystemExit(f"{path}: no non-empty trace rows")

    return rows


def render_svh(rows: list[dict[str, object]], input_path: Path, output_path: Path) -> str:
    timestamp = datetime.now().isoformat(timespec="seconds")
    invocation = " ".join(sys.argv)
    lines: list[str] = []

    lines.append("//========================================================================")
    lines.append(f"// {output_path.name}")
    lines.append("//========================================================================")
    lines.append("// Auto-generated schedule trace oracle")
    lines.append(f"// Source TSV   : {input_path}")
    lines.append(f"// Generated by : {Path(sys.argv[0]).name}")
    lines.append(f"// Invocation   : {invocation}")
    lines.append(f"// Generated at : {timestamp}")
    lines.append("")
    lines.append("// Register order:")
    for idx, reg_name in enumerate(REG_NAMES):
        lines.append(f"//   {idx:2d}: {reg_name}")
    lines.append("")
    lines.append("localparam SCHED_TRACE_STATUS_X = 2'd0;")
    lines.append("localparam SCHED_TRACE_STATUS_I = 2'd1;")
    lines.append("localparam SCHED_TRACE_STATUS_V = 2'd2;")
    lines.append(f"localparam SCHED_TRACE_NUM_ROWS = {len(rows)};")
    lines.append(f"localparam SCHED_TRACE_NUM_REGS = {len(REG_NAMES)};")
    lines.append("")
    lines.append("task init_sched_trace;")
    lines.append("begin")
    lines.append(f"  sched_trace_nrows = {len(rows)};")

    for row_idx, row in enumerate(rows):
        frame_i = row["i"]
        beat_k = row["k"]
        regs = row["regs"]
        lines.append("")
        lines.append(f"  // row {row_idx}: i={frame_i} k={beat_k}")
        lines.append(f"  sched_trace_i[{row_idx}] = 8'd{frame_i};")
        lines.append(f"  sched_trace_k[{row_idx}] = 8'd{beat_k};")
        for reg_idx, (status, value) in enumerate(regs):  # type: ignore[misc]
            lines.append(f"  sched_trace_status[{row_idx}][{reg_idx}] = 2'd{status};")
            lines.append(f"  sched_trace_value[{row_idx}][{reg_idx}] = 16'h{value:04x};")

    lines.append("end")
    lines.append("endtask")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate schedule trace oracle include file.")
    parser.add_argument("--input", type=Path, required=True, help="Input schedule TSV.")
    parser.add_argument("--output", type=Path, required=True, help="Output Verilog include file.")
    args = parser.parse_args()

    rows = load_trace(args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_svh(rows, args.input, args.output), encoding="ascii")


if __name__ == "__main__":
    main()

